<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>013_Promise</title>
  <meta name="description" content="">
  <meta name="author" content="LiJingTang">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="../../images/es6.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <script type="text/javascript" charset="UTF-8">
  // 用Promise对象实现的 Ajax 操作的例子。
  const getJSON = (url) => {
    const promise = new Promise((resolve, reject) => {
      const handler = function() {
        if (this.readyState !== 4) {
          return;
        }
        if (this.status === 200) {
          resolve(this.response);
        } else {
          reject(new Error(this.statusText));
        }
      };
      const client = new XMLHttpRequest();
      client.open('GET', url);
      client.onreadystatechange = handler;
      client.responseType = 'json';
      client.setRequestHeader('Accept', 'application/json');
      client.send();
    });

    return promise;
  };

  {
    function timeout(ms) {
      return new Promise((resolve, reject) => {
        setTimeout(resolve, ms, 'done');
      });
    }
    timeout(2000).then((value) => {
      console.log(value);
    });
  }
  {
    let promise = new Promise(function(resolve, reject) {
      console.log('Promise');
      resolve();
    });
    promise.then(function() {
      console.log('resolved.');
    });
    console.log('Hi!');
  }
  {
    // 异步加载图片
    var loadImage = function loadImageAsync(url) {
      return new Promise(function(resolve, reject) {
        const image = new Image();
        image.onload = function() {
          resolve(image);
        };
        image.onerror = function() {
          reject(new Error('Could not load image at ' + url));
        };
        image.src = url;
      });
    }

    loadImage('http://es6.ruanyifeng.com/favicon.ico').then(() => {
        console.log('加载图片成功');
      }, () => {
        console.log('加载图片失败');
      }
    );
  }
  {
    getJSON('https://api.apiopen.top/recommendPoetry').then((json) => {
      console.log('Contents: ' + json.result.content);
    }, (error) => {
      console.error('出错了', error);
    });
  }
  {
    // 如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数。reject函数的参数通常是Error对象的实例，表示抛出的错误；resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例，比如像下面这样。
    const p1 = new Promise(function (resolve, reject) {
    });
    const p2 = new Promise(function (resolve, reject) {
      resolve(p1);
    });
    // 注意，这时p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1的状态是pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是resolved或者rejected，那么p2的回调函数将会立刻执行。
    const p3 = new Promise(function (resolve, reject) {
      setTimeout(() => reject(new Error('fail')), 3000)
    });
    const p4 = new Promise(function (resolve, reject) {
      setTimeout(() => resolve(p3), 1000)
    });
    p4.then(result => console.log(result)).catch(error => console.log(error));
  }
  {
    // 5
    new Promise((resolve, reject) => {
      resolve(1);
      console.log(2);
    }).then(r => {
      console.log(r);
    });
    // 2
    // 1

    new Promise((resolve, reject) => {
      return resolve(1);
      // 后面的语句不会执行
      console.log(3);
    });
  }
  {
    getJSON('https://api.apiopen.top/singlePoetry').then(
      post => getJSON('https://api.apiopen.top/getSongPoetry?page=1&count=1')
    ).then(
      comments => console.log('resolved: ', comments.result[0].content),
      err => console.log('rejected: ', err)
    );
  }
  {
    const promise = new Promise(function(resolve, reject) {
      resolve('ok');
      throw new Error('test');
    });
    promise.then(function(value) { console.log(value) }).catch(function(error) { console.log(error) });
  }
  {
    const someAsyncThing = function() {
      return new Promise(function(resolve, reject) {
        // 下面一行会报错，因为x没有声明
        resolve(x + 2);
      });
    };
    someAsyncThing().then(function() {
      console.log('everything is great');
    });
    setTimeout(() => { console.log(123) }, 2000);
  }
  {
    let promise = new Promise(function(resolve, reject) {});
    promise.finally(() => {
      // 语句
    });
    // 等同于
    promise.then(
      result => {
        // 语句
        return result;
      },
      error => {
        // 语句
        throw error;
      }
    );

    Promise.prototype.finally = function (callback) {
      let P = this.constructor;
      return this.then(
        value  => P.resolve(callback()).then(() => value),
        reason => P.resolve(callback()).then(() => { throw reason })
      );
    };
  }
  {
    const thenable = {
      then(resolve, reject) {
        reject('出错了');
      }
    };

    Promise.reject(thenable)
    .catch(e => {
      console.log(e === thenable)
    });
  }
  </script>
<body>
  <div>
    <header>
      <h1>Promise</h1>
    </header>

    <div>
      <h5>1.Promise 是异步编程的一种解决方案。简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise 是一个对象，从它可以获取异步操作的消息。Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。</h5>
      <h5>2.Promise对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。</h5>
      <h5>3.一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。</h5>
      <h5>4.Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。</h5>
      <h5>5.调用resolve或reject并不会终结 Promise 的参数函数的执行。</h5>
      <h5>6.一般来说，调用resolve或reject以后，Promise 的使命就完成了，后继操作应该放到then方法里面，而不应该直接写在resolve或reject的后面。所以，最好在它们前面加上return语句，这样就不会有意外。</h5>
      <h5>7.Promise 实例具有then方法，也就是说，then方法是定义在原型对象Promise.prototype上的。它的作用是为 Promise 实例添加状态改变时的回调函数。前面说过，then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。</h5>
      <h5>8.Promise.prototype.catch方法是.then(null, rejection)或.then(undefined, rejection)的别名，用于指定发生错误时的回调函数。对象状态变为resolved，则会调用then方法指定的回调函数；如果异步操作抛出错误，状态就会变为rejected，就会调用catch方法指定的回调函数，处理这个错误。另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获。</h5>
      <h5>9.如果 Promise 状态已经变成resolved，再抛出错误是无效的。</h5>
      <h5>10.Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。</h5>
      <h5>11.一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。理由是可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。因此，建议总是使用catch方法，而不使用then方法的第二个参数。</h5>
      <h5>11-1.跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。</h5>
      <h5>11-2.一般总是建议，Promise 对象后面要跟catch方法，这样可以处理 Promise 内部发生的错误。catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。then方法里面报错，与前面的catch无关了</h5>
      <h5>12.finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。finally方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是fulfilled还是rejected。这表明，finally方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。 finally本质上是then方法的特例。</h5>
      <h5>13.Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。</h5>
    </div>

    <footer>
      <p>
        &copy; Copyright by LiJingTang
      </p>
    </footer>
  </div>
</body>

</html>